name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_INSTALL_DIR: "path/to/directory"
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          cache: true
